apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
  match:
    kind:
      - apiGroups: [""]
        kind: "ClusterRoleBinding"
  parameters:
    allowedSubjects:
      - apiGroup: "rbac.authorization.k8s.io"
        name: "vasanth"
        kind: "User"
    restrictedRole:
        apiGroup: "rbac.authorization.k8s.io"
        name: "cluster-admin"
#        kind: "ClusterRole"
        kinds: [ "RoleBinding", "ClusterRoleBinding" ]
