apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
  match:
    kind:
      - apiGroups: [""]
        kind: "ClusterRoleBinding"
  parameters:
    allowedSubjects:
      - name: "view"
        kind: "ClusterRole"
    restrictedRole:
        apiGroup: "rbac.authorization.k8s.io"
        name: "cluster-admin"
        kind: "ClusterRole"
