---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
#  enforcementAction: dryrun
  match:
    kind:
      - apiGroup: [""]
        kind: RoleBinding
  parameters:
    allowedSubjects:
     - kind: ServiceAccount
       name: default
#       apiGroup: ""
       namespace: default
#     - kind: User      
#       name: vasanthkumar.kalali.ctr@sabre.com
#       namespace: default
#       apiGroup: rbac.authorization.k8s.io
    restrictedRole:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: pod-reader
