---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
  match:
    kind:
      - apiGroups: [""]
        kind: "ClusterRoleBinding"
  parameters:
    allowedSubjects:
      - apiGroup: "rbac.authorization.k8s.io"
        kind: "ServiceAccount"
        name: "vasanth-test"
        namespace: "default"
    restrictedRole:
      apiGroup: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
      name: "cluster-admin"
#      namespace: ""
#      name: "cluster-admin"
