apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings 
spec:
#  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ServiceAccount"]
    namespaceselector:
      matchExpressions:
      - { key: pod_security, operator: notIn, values: [exempt] }
  parameters:
    allowedSubjects: 
      - kind: ServiceAccount
        name: ""
        namespace: default
    restrictedRole:
        apiGroup: rbac.authorization.k8s.io
        kinds: ["RoleBinding","ClusterRoleBinding"] 
        name: ""
        
#       - name: gatekeeper-manager-role

