apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
#  enforcementAction: dryrun
  match:
    kind:
      - apiGroups: ["*"] 
        kind: ["ClusterRoleBinding"]
  parameters:
#    restrictedRole:
#      apiGroup: rbac.authorization.k8s.io
#      kind: ClusterRole
#      name: "*"

    allowedSubjects:
#     - apiGroup: "rbac.authorization.k8s.io"
#      kind: "Group"
#      name: "system:masters"
     - apiGroup: rbac.authorization.k8s.io
       kind: ServiceAccount
       name: "*"
       namespace: "*"
#     - kind: Group
#       apiGroup: rbac.authorization.k8s.io
#       name: system:serviceaccounts
#can create user but not restrcited with other user
#     - apiGroup: "rbac.authorization.k8s.io"
#       kind: User
#       name: vasanth 

    restrictedRole:
      apiGroup: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
      name: "*"
#    allowedSubjects:
#    - apiGroup: "rbac.authorization.k8s.io"
#      kind: "Group"
#      name: "system:masters"






