---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictRoleBindings
metadata:
  name: restrictrolebindings
spec:
#  enforcementAction: dryrun
  match:
    kind:
      - apiGroups: [""]
        kind: "RoleBinding"
  parameters:
    allowedSubjects:
      - apiGroup: "rbac.authorization.k8s.io"
        kind: "ServiceAccount"
        name: "vasanth-test"
        namespace: "default"
    restrictedRole:
        apiGroup: "rbac.authorization.k8s.io"
        kind: "ClusterRole"
#        name: ""
